# Generated by Django 5.2.1 on 2025-05-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_image_alter_destination_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='created',
        ),
    ]
